name: doctl
base: core18
grade: stable
version: git
version-script: cat ./VERSION 
summary: A command line interface for DigitalOcean services
description: doctl is a command line interface to the DigitalOcean public API
confinement: strict

apps:
  doctl:
    command: bin/doctl
    completer: complexion.doctl_bash
    plugs: [network, home]

build-packages:
  - gcc
  - git

parts:
  doctl:
    source: .
    plugin: go
    go-importpath: github.com/digitalocean/doctl
    go-packages: [github.com/digitalocean/doctl/cmd/doctl]
    override-prime: |
      snapcraftctl prime
      doctl completion bash > $SNAPCRAFT_PART_INSTALL/complexion.doctl_bash
      doctl completion zsh > $SNAPCRAFT_PART_INSTALL/complexion.doctl_zsh
