name: doctl
grade: stable
version: git
version-script: cat ./VERSION 
summary: A command line interface for DigitalOcean services
description: doctl is a command line interface to the DigitalOcean public API
confinement: strict

apps:
  doctl:
    command: bin/doctl
    completer: doctl-completer.sh
    plugs: [network, home]

build-packages:
  - gcc
  - git

parts:
  go:
    source-tag: go1.11.4
  doctl:
    after: [go]
    source: .
    plugin: go
    go-importpath: github.com/digitalocean/doctl
    go-packages: [github.com/digitalocean/doctl/cmd/doctl]
    override-stage: |
      snapcraftctl stage
      doctl completion bash > $SNAPCRAFT_PART_INSTALL/doctl-completer.sh
      doctl completion zsh > $SNAPCRAFT_PART_INSTALL/doctl-completer.zsh
