name: doctl
base: core18
grade: stable
version: git
summary: A command line interface for DigitalOcean services
description: doctl is a command line interface to the DigitalOcean public API
confinement: strict

apps:
  doctl:
    command: bin/doctl
    plugs: [network, home]

build-packages:
  - gcc
  - git

parts:
  doctl:
    source: .
    plugin: go
    go-importpath: github.com/digitalocean/doctl
    go-packages: [github.com/digitalocean/doctl/cmd/doctl]
    override-build: |
      snapcraftctl build
      mkdir -p $SNAPCRAFT_PART_INSTALL/bash_completions
      mkdir -p $SNAPCRAFT_PART_INSTALL/zsh_completions
      doctl completion bash > $SNAPCRAFT_PART_INSTALL/bash_completions/doctl
      doctl completion zsh > $SNAPCRAFT_PART_INSTALL/zsh_completions/doctl
